### PR TITLE
Cleaned Up. Interface working

### PR DESCRIPTION
**Pull request by EricoDeMecha**
Still need some more styling though.

### CODE REVIEW

**Comment by kimanimichael** [comment]
App doesn't run properly when you separate them in this way . Have you tried running both sets of code?

**Comment by EricoDeMecha** [comment]
Yes, I tried running your original code but it did not work. So I did some
few edits and it did run except I didn't all the other errors in the other
screens. But the main screen is working fine.

**Comment by kimanimichael** [comment]
Hey. Eric The reason the original code isn't running is because I tried to access variables of the method csales() outside the class TodaySales(). Comment out lines 135,136 and 137 and the code should run just fine.

**Comment by EricoDeMecha** [comment]
Yeah, it's working fine. My bad, I should have communicated before making
those changes.

**Comment by kimanimichael** [comment]
It's okay..

**Pull request closed without merging**
